/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import RMI.Barang;
import RMI.DetailTransaksi;
import RMI.Keranjang;
import RMI.Transaksi;
import RMI.service;
import java.rmi.Naming;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        viewKeranjang();
        sum();
        view_transaksi();
        tracking_cbUbahStatus.setVisible(false);
        tracking_btnSubmit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barang_rbgUkuranBarang = new javax.swing.ButtonGroup();
        frame_detailTransaksi = new javax.swing.JFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        frame2_tblDetailTransaksi = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        pembayaran_rbgJenisPengiriman = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_customer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customer_nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customer_noHp = new javax.swing.JTextField();
        customer_btnSimpan = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        customer_alamat = new javax.swing.JTextArea();
        panel_barang = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        barang_namaBarang = new javax.swing.JTextField();
        barang_btnSimpan = new javax.swing.JButton();
        barang_beratBarang = new javax.swing.JSpinner();
        barang_cbJenisBarang = new javax.swing.JComboBox<>();
        panel_pembayaran = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pembayaran_tblKeranjang = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        pembayaran_totalHarga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pembayaran_pembayaran = new javax.swing.JTextField();
        pembayaran_btnBayar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pembayaran_penerima = new javax.swing.JTextField();
        pembayaran_pengirim = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        pembayaran_alamatTujuan = new javax.swing.JTextArea();
        pembayaran_btnHapusTbl = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        pembayaran_rbReguler = new javax.swing.JRadioButton();
        pembayaran_rbExpress = new javax.swing.JRadioButton();
        panel_tracking = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tracking_idTransaksi = new javax.swing.JTextField();
        tracking_btnCari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tracking_tblTracking = new javax.swing.JTable();
        tracking_btnUbahStatus = new javax.swing.JButton();
        tracking_cbUbahStatus = new javax.swing.JComboBox<>();
        tracking_btnSubmit = new javax.swing.JButton();
        panel_riwayatTransaksi = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        riwayatTransaksi_tblRiwayat = new javax.swing.JTable();
        riwayatTransaksi_btnLihatDetail = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        frame_detailTransaksi.setLocation(new java.awt.Point(100, 100));
        frame_detailTransaksi.setSize(new java.awt.Dimension(600, 200));

        frame2_tblDetailTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "ID Barang", "Nama Barang", "Jenis Barang", "Berat(Kg)", "Sub Total"
            }
        ));
        jScrollPane5.setViewportView(frame2_tblDetailTransaksi);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Detail Transaksi");

        javax.swing.GroupLayout frame_detailTransaksiLayout = new javax.swing.GroupLayout(frame_detailTransaksi.getContentPane());
        frame_detailTransaksi.getContentPane().setLayout(frame_detailTransaksiLayout);
        frame_detailTransaksiLayout.setHorizontalGroup(
            frame_detailTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_detailTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frame_detailTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGroup(frame_detailTransaksiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        frame_detailTransaksiLayout.setVerticalGroup(
            frame_detailTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_detailTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama        :");

        jLabel2.setText("Alamat      :");

        jLabel3.setText("No Hp       :");

        customer_btnSimpan.setText("Simpan");
        customer_btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_btnSimpanActionPerformed(evt);
            }
        });

        customer_alamat.setColumns(20);
        customer_alamat.setRows(5);
        jScrollPane6.setViewportView(customer_alamat);

        javax.swing.GroupLayout panel_customerLayout = new javax.swing.GroupLayout(panel_customer);
        panel_customer.setLayout(panel_customerLayout);
        panel_customerLayout.setHorizontalGroup(
            panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customer_noHp, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(customer_nama)
                    .addComponent(customer_btnSimpan)
                    .addComponent(jScrollPane6))
                .addContainerGap(364, Short.MAX_VALUE))
        );
        panel_customerLayout.setVerticalGroup(
            panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(customer_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_noHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customer_btnSimpan)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", panel_customer);

        jLabel5.setText("Nama Barang   :");

        jLabel7.setText("Jenis Barang :");

        jLabel8.setText("Berat Barang   :");

        barang_namaBarang.setToolTipText("");

        barang_btnSimpan.setText("Tambah");
        barang_btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barang_btnSimpanActionPerformed(evt);
            }
        });

        barang_cbJenisBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elektronik", "Farmasi", "Pakaian", "Makanan dan Minuman", "Kosmetik", "Otomotif" }));

        javax.swing.GroupLayout panel_barangLayout = new javax.swing.GroupLayout(panel_barang);
        panel_barang.setLayout(panel_barangLayout);
        panel_barangLayout.setHorizontalGroup(
            panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_barangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barang_btnSimpan)
                    .addComponent(barang_beratBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(barang_namaBarang)
                    .addComponent(barang_cbJenisBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        panel_barangLayout.setVerticalGroup(
            panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_barangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(barang_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(barang_cbJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(barang_beratBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barang_btnSimpan)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Barang", panel_barang);

        jLabel11.setText("Barang");

        pembayaran_tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Ukuran Barang", "Berat Barang", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(pembayaran_tblKeranjang);

        jLabel12.setText("Total Harga     :");

        pembayaran_totalHarga.setEditable(false);

        jLabel13.setText("Pembayaran    : ");

        pembayaran_btnBayar.setText("Bayar");
        pembayaran_btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaran_btnBayarActionPerformed(evt);
            }
        });

        jLabel9.setText("Alamat Tujuan :");

        jLabel10.setText("Penerima         :");

        jLabel15.setText("Pengirim          :");

        pembayaran_alamatTujuan.setColumns(20);
        pembayaran_alamatTujuan.setRows(5);
        jScrollPane4.setViewportView(pembayaran_alamatTujuan);

        pembayaran_btnHapusTbl.setText("Hapus");
        pembayaran_btnHapusTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaran_btnHapusTblActionPerformed(evt);
            }
        });

        jLabel16.setText("Jenis Pengiriman:");

        pembayaran_rbgJenisPengiriman.add(pembayaran_rbReguler);
        pembayaran_rbReguler.setText("Reguler");
        pembayaran_rbReguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaran_rbRegulerActionPerformed(evt);
            }
        });

        pembayaran_rbgJenisPengiriman.add(pembayaran_rbExpress);
        pembayaran_rbExpress.setText("Express");
        pembayaran_rbExpress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaran_rbExpressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_pembayaranLayout = new javax.swing.GroupLayout(panel_pembayaran);
        panel_pembayaran.setLayout(panel_pembayaranLayout);
        panel_pembayaranLayout.setHorizontalGroup(
            panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(panel_pembayaranLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pembayaran_btnHapusTbl))
                    .addGroup(panel_pembayaranLayout.createSequentialGroup()
                        .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13))
                        .addGap(27, 27, 27)
                        .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pembayaran_btnBayar)
                            .addComponent(pembayaran_pembayaran)
                            .addComponent(pembayaran_totalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                    .addGroup(panel_pembayaranLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(23, 23, 23)
                        .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_pembayaranLayout.createSequentialGroup()
                                .addComponent(pembayaran_rbReguler)
                                .addGap(18, 18, 18)
                                .addComponent(pembayaran_rbExpress))
                            .addComponent(pembayaran_pengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pembayaran_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        panel_pembayaranLayout.setVerticalGroup(
            panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pembayaranLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(pembayaran_btnHapusTbl))
                    .addGroup(panel_pembayaranLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pembayaran_pengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pembayaran_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(pembayaran_rbReguler)
                    .addComponent(pembayaran_rbExpress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pembayaran_totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pembayaran_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pembayaran_btnBayar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pembayaran", panel_pembayaran);

        panel_tracking.setName("Tracking"); // NOI18N

        jLabel14.setText("ID Transaksi :");

        tracking_btnCari.setText("Cari");
        tracking_btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracking_btnCariActionPerformed(evt);
            }
        });

        tracking_tblTracking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Pengirim", "Penerima", "Alamat Tujuan", "Jenis Pengiriman", "Total Harga", "Pembayaran", "Tanggal Transaksi", "Status Barang"
            }
        ));
        jScrollPane2.setViewportView(tracking_tblTracking);

        tracking_btnUbahStatus.setText("Ubah Status");
        tracking_btnUbahStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracking_btnUbahStatusActionPerformed(evt);
            }
        });

        tracking_cbUbahStatus.setEditable(true);
        tracking_cbUbahStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diproses", "Dikemas", "Dikirim", "Sampai kota tujuan", "Diterima" }));

        tracking_btnSubmit.setText("Submit");
        tracking_btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracking_btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_trackingLayout = new javax.swing.GroupLayout(panel_tracking);
        panel_tracking.setLayout(panel_trackingLayout);
        panel_trackingLayout.setHorizontalGroup(
            panel_trackingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_trackingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_trackingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addGroup(panel_trackingLayout.createSequentialGroup()
                        .addGroup(panel_trackingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_trackingLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addGroup(panel_trackingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tracking_btnCari)
                                    .addComponent(tracking_idTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tracking_btnUbahStatus)
                            .addComponent(tracking_cbUbahStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tracking_btnSubmit))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_trackingLayout.setVerticalGroup(
            panel_trackingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_trackingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_trackingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tracking_idTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tracking_btnCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tracking_btnUbahStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tracking_cbUbahStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tracking_btnSubmit)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tracking", panel_tracking);

        riwayatTransaksi_tblRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Pengirim", "Penerima", "Alamat Tujuan", "Jenis Pengiriman", "Total Harga", "Pembayaran", "Tanggal Transaksi"
            }
        ));
        jScrollPane3.setViewportView(riwayatTransaksi_tblRiwayat);

        riwayatTransaksi_btnLihatDetail.setText("Lihat Detail");
        riwayatTransaksi_btnLihatDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatTransaksi_btnLihatDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_riwayatTransaksiLayout = new javax.swing.GroupLayout(panel_riwayatTransaksi);
        panel_riwayatTransaksi.setLayout(panel_riwayatTransaksiLayout);
        panel_riwayatTransaksiLayout.setHorizontalGroup(
            panel_riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_riwayatTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addGroup(panel_riwayatTransaksiLayout.createSequentialGroup()
                        .addComponent(riwayatTransaksi_btnLihatDetail)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_riwayatTransaksiLayout.setVerticalGroup(
            panel_riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_riwayatTransaksiLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(riwayatTransaksi_btnLihatDetail)
                .addGap(0, 74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Riwayat Transaksi", panel_riwayatTransaksi);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Operator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tracking_btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracking_btnCariActionPerformed
        String id = tracking_idTransaksi.getText();
        DefaultTableModel model = (DefaultTableModel) tracking_tblTracking.getModel();
        model.setRowCount(0);
        viewTrackingTransaksi(id);
    }//GEN-LAST:event_tracking_btnCariActionPerformed


    private void customer_btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_btnSimpanActionPerformed

        try {
            String nama = customer_nama.getText();
            String alamat = customer_alamat.getText();
            String no_hp = customer_noHp.getText();

            if (nama.isEmpty() || alamat.isEmpty() || no_hp.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap isi semua data", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                service Service = (service) Naming.lookup("rmi://localhost:5098/db");
                String result = Service.input_pelanggan(nama, alamat, no_hp);

                pembayaran_pengirim.setText(nama);

                customer_nama.setText("");
                customer_alamat.setText("");
                customer_noHp.setText("");
                JOptionPane.showMessageDialog(null, result, "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_customer_btnSimpanActionPerformed

    private void barang_btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barang_btnSimpanActionPerformed
        try {
            String nama_barang = barang_namaBarang.getText();
            String jenis_barang = barang_cbJenisBarang.getSelectedItem().toString();
            int berat = (int) barang_beratBarang.getValue();
            int sub_total = berat * 3000; //harga per Kg

            if (nama_barang.isEmpty() || jenis_barang.isEmpty() || berat == 0) {
                JOptionPane.showMessageDialog(null, "Harap isi semua data", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {

                service Service = (service) Naming.lookup("rmi://localhost:5098/db");
                String result = Service.input_barang(nama_barang, jenis_barang, berat, sub_total);
                int last_id = Integer.parseInt(Service.lastInput_barang());
                Service.input_keranjang(nama_barang, last_id, jenis_barang, berat, sub_total);

                barang_namaBarang.setText("");
                barang_beratBarang.setValue(0);

                DefaultTableModel model = (DefaultTableModel) pembayaran_tblKeranjang.getModel();
                model.setRowCount(0);
                viewKeranjang();
                sum();

                JOptionPane.showMessageDialog(null, result, "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_barang_btnSimpanActionPerformed

    private void pembayaran_btnHapusTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaran_btnHapusTblActionPerformed
        String id = pembayaran_tblKeranjang.getValueAt(pembayaran_tblKeranjang.getSelectedRow(), 0).toString();
        try {
            service Service = (service) Naming.lookup("rmi://localhost:5098/db");
            Service.dalete_keranjang(id);
            Service.dalete_barang(id);

            DefaultTableModel model = (DefaultTableModel) pembayaran_tblKeranjang.getModel();
            model.setRowCount(0);
            viewKeranjang();
            sum();

            JOptionPane.showMessageDialog(null, "Delete barang sukses", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pembayaran_btnHapusTblActionPerformed

    private void riwayatTransaksi_btnLihatDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatTransaksi_btnLihatDetailActionPerformed
        frame_detailTransaksi.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) frame2_tblDetailTransaksi.getModel();
        model.setRowCount(0);
        viewDetailTransaksi();
    }//GEN-LAST:event_riwayatTransaksi_btnLihatDetailActionPerformed

    private void pembayaran_rbRegulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaran_rbRegulerActionPerformed
        sum();
    }//GEN-LAST:event_pembayaran_rbRegulerActionPerformed

    private void pembayaran_rbExpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaran_rbExpressActionPerformed
        sum();
    }//GEN-LAST:event_pembayaran_rbExpressActionPerformed

    private void pembayaran_btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaran_btnBayarActionPerformed
        try {
            int countkeranjang = (int) pembayaran_tblKeranjang.getRowCount();
            String pengirim = pembayaran_pengirim.getText();
            String penerima = pembayaran_penerima.getText();
            String alamat = pembayaran_alamatTujuan.getText();
            String jenis_pengiriman = "";
            if (pembayaran_rbReguler.isSelected()) {
                jenis_pengiriman = "Reguler";
            } else if (pembayaran_rbExpress.isSelected()) {
                jenis_pengiriman = "Express";
            }
            int total_harga = Integer.parseInt(pembayaran_totalHarga.getText());
            int Pembayaran = Integer.parseInt(pembayaran_pembayaran.getText());
            String status_barang = "Diproses";

            if (pengirim.isEmpty() || penerima.isEmpty() || alamat.isEmpty() || jenis_pengiriman.isEmpty() || Pembayaran == 0) {
                JOptionPane.showMessageDialog(null, "Harap isi semua data", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (countkeranjang < 1) {
                JOptionPane.showMessageDialog(null, "Anda belum memiliki barang untuk dikirim", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (Pembayaran < total_harga) {
                JOptionPane.showMessageDialog(null, "Uang yang anda miliki tidak mencukupi untuk melakukan transaksi", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {

                service Service = (service) Naming.lookup("rmi://localhost:5098/db");
                Service.input_transaksi(pengirim, penerima, alamat, jenis_pengiriman, total_harga, Pembayaran, status_barang);

                input_detail();

                Service.truncate_keranjang();

                DefaultTableModel model = (DefaultTableModel) pembayaran_tblKeranjang.getModel();
                model.setRowCount(0);
                viewKeranjang();
                sum();
                DefaultTableModel model2 = (DefaultTableModel) riwayatTransaksi_tblRiwayat.getModel();
                model2.setRowCount(0);
                view_transaksi();

                pembayaran_pengirim.setText("");
                pembayaran_penerima.setText("");
                pembayaran_alamatTujuan.setText("");
                pembayaran_pembayaran.setText("");

                JOptionPane.showMessageDialog(null, "Transaksi sukses", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pembayaran_btnBayarActionPerformed

    private void tracking_btnUbahStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracking_btnUbahStatusActionPerformed
        tracking_cbUbahStatus.setVisible(true);
        tracking_btnSubmit.setVisible(true);
    }//GEN-LAST:event_tracking_btnUbahStatusActionPerformed

    private void tracking_btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracking_btnSubmitActionPerformed
        String id = tracking_tblTracking.getValueAt(tracking_tblTracking.getSelectedRow(), 0).toString();
        String status = tracking_cbUbahStatus.getSelectedItem().toString();
        //System.out.println("GUI.User.tracking_btnSubmitActionPerformed() id="+id);
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih transaksi terlebih dahulu", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                service Service = (service) Naming.lookup("rmi://localhost:5098/db");
                Service.updateStatus(id, status);
                JOptionPane.showMessageDialog(null, "Update sukses ", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                DefaultTableModel model = (DefaultTableModel) tracking_tblTracking.getModel();
                model.setRowCount(0);
                viewTrackingTransaksi(id);

                tracking_cbUbahStatus.setVisible(false);
                tracking_btnSubmit.setVisible(false);
            } catch (Exception e) {
                System.out.println("GUI.User.tracking_btnSubmitActionPerformed()" + e);
            }
        }
    }//GEN-LAST:event_tracking_btnSubmitActionPerformed

    public void viewBarang() {
        try {
            service Service = (service) Naming.lookup("rmi://localhost:5098/db");
            ArrayList<Barang> list = Service.dataBarang();
            DefaultTableModel model = (DefaultTableModel) pembayaran_tblKeranjang.getModel();
            Object[] row = new Object[4];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getNama_barang();
                row[1] = list.get(i).getUkuran();
                row[2] = list.get(i).getBerat() + " Kg";
                row[3] = "Rp. " + list.get(i).getSub_total();
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println("GUI.User.viewBarang() " + e.toString());
        }
    }

    public void viewKeranjang() {
        try {
            service Service = (service) Naming.lookup("rmi://localhost:5098/db");
            ArrayList<Keranjang> list = Service.dataKeranjang();
            DefaultTableModel model = (DefaultTableModel) pembayaran_tblKeranjang.getModel();
            Object[] row = new Object[5];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getId_barang();
                row[1] = list.get(i).getNama_barang();
                row[2] = list.get(i).getJenis_barang();
                row[3] = list.get(i).getBerat() + " Kg";
                row[4] = "Rp. " + list.get(i).getSub_total();
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println("GUI.User.viewKeranjang() " + e.toString());
        }
    }

    public void sum() {
        try {
            service Service = (service) Naming.lookup("rmi://localhost:5098/db");
            Integer total = Integer.parseInt(Service.sum_subTotal());
            //System.out.println("GUI.User.sum() = "+total);
            if (total == 0) {
                pembayaran_totalHarga.setText("0");
            } else {
                if (pembayaran_rbReguler.isSelected()) {
                    total = total + 15000;
                } else if (pembayaran_rbExpress.isSelected()) {
                    total = total + 25000;
                }
                String totali = total.toString();
                pembayaran_totalHarga.setText(totali);
            }

        } catch (Exception e) {
            System.out.println("GUI.User.sum() " + e.toString());
        }
    }

    public void input_detail() {
        try {
            service Service = (service) Naming.lookup("rmi://localhost:5098/db");
            ArrayList<Keranjang> list = Service.dataKeranjang();
            int last_id = Integer.parseInt(Service.lastInput_transaksi());
            Object[] row = new Object[5];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getId_barang();
                row[1] = list.get(i).getNama_barang();
                row[2] = list.get(i).getJenis_barang();
                row[3] = list.get(i).getBerat();
                row[4] = list.get(i).getSub_total();
                int id_barang = Integer.parseInt(row[0].toString());
                String nama_barang = row[1].toString();
                String jenis_barang = row[2].toString();
                int berat = Integer.parseInt(row[3].toString());
                int sub_total = Integer.parseInt(row[4].toString());
                Service.input_detailTransaksi(last_id, id_barang, nama_barang, jenis_barang, berat, sub_total);
            }

        } catch (Exception e) {
            System.out.println("GUI.User.input_detail() " + e.toString());
        }
    }

    public void view_transaksi() {
        try {
            service Service = (service) Naming.lookup("rmi://localhost:5098/db");
            ArrayList<Transaksi> list = Service.dataTransaksi();
            DefaultTableModel model = (DefaultTableModel) riwayatTransaksi_tblRiwayat.getModel();
            Object[] row = new Object[8];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getId_transaksi();
                row[1] = list.get(i).getPengirim();
                row[2] = list.get(i).getPenerima();
                row[3] = list.get(i).getAlamat_tujuan();
                row[4] = list.get(i).getJenis_pengiriman();
                row[5] = list.get(i).getTotal_harga();
                row[6] = list.get(i).getPembayaran();
                row[7] = list.get(i).getTanggal_transaksi();
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println("GUI.User.view_transaksi() " + e.toString());
        }
    }

    public void viewTrackingTransaksi(String id) {
        try {
            service Service = (service) Naming.lookup("rmi://localhost:5098/db");
            ArrayList<Transaksi> list = Service.operator_tracking(id);
            DefaultTableModel model = (DefaultTableModel) tracking_tblTracking.getModel();
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Object[] row = new Object[9];
                for (int i = 0; i < list.size(); i++) {
                    row[0] = list.get(i).getId_transaksi();
                    row[1] = list.get(i).getPengirim();
                    row[2] = list.get(i).getPenerima();
                    row[3] = list.get(i).getAlamat_tujuan();
                    row[4] = list.get(i).getJenis_pengiriman();
                    row[5] = list.get(i).getTotal_harga();
                    row[6] = list.get(i).getPembayaran();
                    row[7] = list.get(i).getTanggal_transaksi();
                    row[8] = list.get(i).getStatus_barang();
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            System.out.println("GUI.User.view_transaksi() " + e.toString());
        }
    }

    public void viewDetailTransaksi() {
        String id = riwayatTransaksi_tblRiwayat.getValueAt(riwayatTransaksi_tblRiwayat.getSelectedRow(), 0).toString();
        try {
            service Service = (service) Naming.lookup("rmi://localhost:5098/db");
            ArrayList<DetailTransaksi> list = Service.dataDetailTransaksi(id);

            DefaultTableModel model = (DefaultTableModel) frame2_tblDetailTransaksi.getModel();
            Object[] row = new Object[6];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getId_transaksi();
                row[1] = list.get(i).getId_barang();
                row[2] = list.get(i).getNama_barang();
                row[3] = list.get(i).getJenis_barang();
                row[4] = list.get(i).getBerat() + " Kg";
                row[5] = "Rp. " + list.get(i).getSub_total();
                model.addRow(row);
            }

        } catch (Exception e) {
            System.out.println("GUI.User.viewDetailTransaksi() " + e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner barang_beratBarang;
    private javax.swing.JButton barang_btnSimpan;
    private javax.swing.JComboBox<String> barang_cbJenisBarang;
    private javax.swing.JTextField barang_namaBarang;
    private javax.swing.ButtonGroup barang_rbgUkuranBarang;
    private javax.swing.JTextArea customer_alamat;
    private javax.swing.JButton customer_btnSimpan;
    private javax.swing.JTextField customer_nama;
    private javax.swing.JTextField customer_noHp;
    private javax.swing.JTable frame2_tblDetailTransaksi;
    private javax.swing.JFrame frame_detailTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel_barang;
    private javax.swing.JPanel panel_customer;
    private javax.swing.JPanel panel_pembayaran;
    private javax.swing.JPanel panel_riwayatTransaksi;
    private javax.swing.JPanel panel_tracking;
    private javax.swing.JTextArea pembayaran_alamatTujuan;
    private javax.swing.JButton pembayaran_btnBayar;
    private javax.swing.JButton pembayaran_btnHapusTbl;
    private javax.swing.JTextField pembayaran_pembayaran;
    private javax.swing.JTextField pembayaran_penerima;
    private javax.swing.JTextField pembayaran_pengirim;
    private javax.swing.JRadioButton pembayaran_rbExpress;
    private javax.swing.JRadioButton pembayaran_rbReguler;
    private javax.swing.ButtonGroup pembayaran_rbgJenisPengiriman;
    private javax.swing.JTable pembayaran_tblKeranjang;
    private javax.swing.JTextField pembayaran_totalHarga;
    private javax.swing.JButton riwayatTransaksi_btnLihatDetail;
    private javax.swing.JTable riwayatTransaksi_tblRiwayat;
    private javax.swing.JButton tracking_btnCari;
    private javax.swing.JButton tracking_btnSubmit;
    private javax.swing.JButton tracking_btnUbahStatus;
    private javax.swing.JComboBox<String> tracking_cbUbahStatus;
    private javax.swing.JTextField tracking_idTransaksi;
    private javax.swing.JTable tracking_tblTracking;
    // End of variables declaration//GEN-END:variables
}
